import type { VoiceModel } from "@saas/types";

export const PRESET_VOICES: readonly VoiceModel[] = [
  {
    id: "b347db033a6549378b48d00acb0d06cd",
    name: "Selene",
    gender: "female",
    category: "meditation",
    language: "en-US",
    languageName: "English (United States) 🇺🇸",
    previewAudioUrl: "/audio/previews/selene.mp3",
    avatarUrl: "/avatars/selene.webp",
    supportedEmotions: ["neutral", "whispering", "empathetic"],
    isPremium: true,
    tags: ["Meditative", "Calm", "Soft", "Mindfulness"],
  },
  {
    id: "bf322df2096a46f18c579d0baa36f41d",
    name: "Adrian",
    gender: "male",
    category: "narrative",
    language: "en-US",
    languageName: "English (United States) 🇺🇸",
    previewAudioUrl: "/audio/previews/adrian.mp3",
    avatarUrl: "/avatars/adrian.webp",
    supportedEmotions: ["neutral", "authoritative", "dramatic"],
    isPremium: true,
    tags: ["Steady", "Reliable Narrator", "Audiobook", "Documentary"],
  },
  {
    id: "933563129e564b19a115bedd57b7406a",
    name: "Sarah",
    gender: "female",
    category: "commercial",
    language: "en-US",
    languageName: "English (United States) 🇺🇸",
    previewAudioUrl: "/audio/previews/sarah.mp3",
    avatarUrl: "/avatars/sarah.webp",
    supportedEmotions: ["neutral", "cheerful", "excited"],
    isPremium: true,
    tags: ["Engaged Speaker", "Commercial", "Upbeat", "Social Media"],
  },
  {
    id: "536d3a5e000945adb7038665781a4aca",
    name: "Ethan",
    gender: "male",
    category: "educational",
    language: "en-US",
    languageName: "English (United States) 🇺🇸",
    previewAudioUrl: "/audio/previews/ethan.mp3",
    avatarUrl: "/avatars/ethan.webp",
    supportedEmotions: ["neutral", "cheerful"],
    isPremium: true,
    tags: ["Curious Explainer", "Tech", "E-Learning", "Clear"],
  },
  {
    id: "e3cd384158934cc9a01029cd7d278634",
    name: "Laura",
    gender: "female",
    category: "executive",
    language: "en-US",
    languageName: "English (United States) 🇺🇸",
    previewAudioUrl: "/audio/previews/laura.mp3",
    avatarUrl: "/avatars/laura.webp",
    supportedEmotions: ["neutral", "authoritative", "empathetic"],
    isPremium: true,
    tags: ["Confident Narrator", "Executive", "Corporate", "Presentation"],
  },
  {
    id: "79d0bd3e4e5444b18f7b6d89b5927bf1",
    name: "Jordan",
    gender: "male",
    category: "commercial",
    language: "en-US",
    languageName: "English (United States) 🇺🇸",
    previewAudioUrl: "/audio/previews/jordan.mp3",
    avatarUrl: "/avatars/jordan.webp",
    supportedEmotions: ["neutral", "excited", "dramatic"],
    isPremium: true,
    tags: ["Motivational Speaker", "Dynamic", "Inspiring", "Podcast"],
  },
  {
    id: "9a9cf47702da476aa4629e2506d4a857",
    name: "Hannah",
    gender: "female",
    category: "conversational",
    language: "en-US",
    languageName: "English (United States) 🇺🇸",
    previewAudioUrl: "/audio/previews/hannah.mp3",
    avatarUrl: "/avatars/hannah.webp",
    supportedEmotions: ["neutral", "cheerful", "empathetic"],
    isPremium: true,
    tags: ["Conversation Specialist", "Friendly", "Warm", "Podcast"],
  },
] as const;

export const DEFAULT_VOICE_ID = "b347db033a6549378b48d00acb0d06cd";

export const DEFAULT_VOICE_SETTINGS = {
  stability: 0.75,
  similarityBoost: 0.85,
  style: 0.45,
  speed: 1.0,
  pitch: 0,
} as const;
