import type { VoiceModel } from "@saas/types";

export const PRESET_VOICES: readonly VoiceModel[] = [
  // ===================== English (United States) =====================
  {
    id: "7f92f8afb8ec43bf81429cc1c9199cb1",
    name: "Aurora Vance",
    gender: "female",
    category: "narrative",
    language: "en-US",
    languageName: "English (United States) 🇺🇸",
    previewAudioUrl: "/audio/previews/aurora.mp3",
    avatarUrl: "/avatars/aurora.webp",
    supportedEmotions: ["neutral", "empathetic", "whispering", "dramatic"],
    isPremium: true,
    tags: ["Warm", "Audiobook", "Cinematic", "Deep"],
  },
  {
    id: "547432130e6243679fa77f98555e09f5",
    name: "Elena Rostova",
    gender: "female",
    category: "conversational",
    language: "en-US",
    languageName: "English (United States) 🇺🇸",
    previewAudioUrl: "/audio/previews/elena.mp3",
    avatarUrl: "/avatars/elena.webp",
    supportedEmotions: ["neutral", "cheerful", "excited", "empathetic"],
    isPremium: false,
    tags: ["Friendly", "Podcast", "Upbeat", "Natural"],
  },
  {
    id: "e44c2084c810453d8542ab4c23db2ff7",
    name: "Kai Takahashi",
    gender: "male",
    category: "commercial",
    language: "en-US",
    languageName: "English (United States) 🇺🇸",
    previewAudioUrl: "/audio/previews/kai.mp3",
    avatarUrl: "/avatars/kai.webp",
    supportedEmotions: ["neutral", "cheerful", "excited"],
    isPremium: false,
    tags: ["Youthful", "Promo", "Tech", "Energetic"],
  },
  {
    id: "8c7f991bb5a242c7a36df1b3cebc2412",
    name: "David Sterling",
    gender: "male",
    category: "narrative",
    language: "en-US",
    languageName: "English (United States) 🇺🇸",
    previewAudioUrl: "/audio/previews/david.mp3",
    avatarUrl: "/avatars/david.webp",
    supportedEmotions: ["neutral", "authoritative", "dramatic"],
    isPremium: true,
    tags: ["Documentary", "Deep Voice", "Storytelling", "Authoritative"],
  },
  {
    id: "3e5a7b8c9d0e1f2a3b4c5d6e7f8a9b0c",
    name: "Chloe Brooks",
    gender: "female",
    category: "commercial",
    language: "en-US",
    languageName: "English (United States) 🇺🇸",
    previewAudioUrl: "/audio/previews/chloe.mp3",
    avatarUrl: "/avatars/chloe.webp",
    supportedEmotions: ["neutral", "cheerful", "excited"],
    isPremium: false,
    tags: ["Commercial", "Lively", "Bright", "Social Media"],
  },
  {
    id: "4f6b8c9d0e1f2a3b4c5d6e7f8a9b0c1d",
    name: "Alexander Hayes",
    gender: "male",
    category: "executive",
    language: "en-US",
    languageName: "English (United States) 🇺🇸",
    previewAudioUrl: "/audio/previews/alexander.mp3",
    avatarUrl: "/avatars/alexander.webp",
    supportedEmotions: ["neutral", "authoritative"],
    isPremium: true,
    tags: ["Executive", "Corporate", "Presentation", "Confident"],
  },
  {
    id: "5a7c9d0e1f2a3b4c5d6e7f8a9b0c1d2e",
    name: "Harper Collins",
    gender: "female",
    category: "meditation",
    language: "en-US",
    languageName: "English (United States) 🇺🇸",
    previewAudioUrl: "/audio/previews/harper.mp3",
    avatarUrl: "/avatars/harper.webp",
    supportedEmotions: ["neutral", "empathetic", "whispering"],
    isPremium: false,
    tags: ["Mindfulness", "Calm", "Soothing", "Sleep Story"],
  },
  {
    id: "6b8d0e1f2a3b4c5d6e7f8a9b0c1d2e3f",
    name: "Ethan Wright",
    gender: "male",
    category: "gaming",
    language: "en-US",
    languageName: "English (United States) 🇺🇸",
    previewAudioUrl: "/audio/previews/ethan.mp3",
    avatarUrl: "/avatars/ethan.webp",
    supportedEmotions: ["neutral", "dramatic", "excited"],
    isPremium: true,
    tags: ["Gaming", "Action Hero", "Grit", "Cinematic"],
  },

  // ===================== English (United Kingdom) =====================
  {
    id: "8c7f991bb5a242c7a36df1b3cebc2411",
    name: "Marcus Sterling",
    gender: "male",
    category: "commercial",
    language: "en-GB",
    languageName: "English (United Kingdom) 🇬🇧",
    previewAudioUrl: "/audio/previews/marcus.mp3",
    avatarUrl: "/avatars/marcus.webp",
    supportedEmotions: ["neutral", "authoritative", "dramatic"],
    isPremium: true,
    tags: ["British", "Executive", "Documentary", "Crisp"],
  },
  {
    id: "7c9e1f2a3b4c5d6e7f8a9b0c1d2e3f4a",
    name: "Victoria Ashford",
    gender: "female",
    category: "narrative",
    language: "en-GB",
    languageName: "English (United Kingdom) 🇬🇧",
    previewAudioUrl: "/audio/previews/victoria.mp3",
    avatarUrl: "/avatars/victoria.webp",
    supportedEmotions: ["neutral", "dramatic", "empathetic"],
    isPremium: true,
    tags: ["British Royal", "Audiobook", "Elegant", "Literature"],
  },
  {
    id: "8d0f2a3b4c5d6e7f8a9b0c1d2e3f4a5b",
    name: "Oliver Pendelton",
    gender: "male",
    category: "conversational",
    language: "en-GB",
    languageName: "English (United Kingdom) 🇬🇧",
    previewAudioUrl: "/audio/previews/oliver.mp3",
    avatarUrl: "/avatars/oliver.webp",
    supportedEmotions: ["neutral", "cheerful", "authoritative"],
    isPremium: false,
    tags: ["British BBC", "News", "Podcast", "Articulate"],
  },
  {
    id: "9e1a3b4c5d6e7f8a9b0c1d2e3f4a5b6c",
    name: "Eleanor Finch",
    gender: "female",
    category: "commercial",
    language: "en-GB",
    languageName: "English (United Kingdom) 🇬🇧",
    previewAudioUrl: "/audio/previews/eleanor.mp3",
    avatarUrl: "/avatars/eleanor.webp",
    supportedEmotions: ["neutral", "cheerful", "empathetic"],
    isPremium: false,
    tags: ["British Promo", "Luxury", "Warm", "Sophisticated"],
  },

  // ===================== English (Australia & Canada) =====================
  {
    id: "1c3e5a7b8c9d0e1f2a3b4c5d6e7f8a9b",
    name: "Seraphina Lin",
    gender: "female",
    category: "meditation",
    language: "en-AU",
    languageName: "English (Australia) 🇦🇺",
    previewAudioUrl: "/audio/previews/seraphina.mp3",
    avatarUrl: "/avatars/seraphina.webp",
    supportedEmotions: ["neutral", "empathetic", "whispering"],
    isPremium: true,
    tags: ["Calm", "Mindfulness", "Soft", "Aussie"],
  },
  {
    id: "2d4f6b8c9d0e1f2a3b4c5d6e7f8a9b0c",
    name: "Jack Callahan",
    gender: "male",
    category: "commercial",
    language: "en-AU",
    languageName: "English (Australia) 🇦🇺",
    previewAudioUrl: "/audio/previews/jack.mp3",
    avatarUrl: "/avatars/jack.webp",
    supportedEmotions: ["neutral", "cheerful", "excited"],
    isPremium: false,
    tags: ["Aussie Casual", "Outdoor", "Commercial", "Friendly"],
  },
  {
    id: "3e5a7c9d0e1f2a3b4c5d6e7f8a9b0c1d",
    name: "Lucas Tremblay",
    gender: "male",
    category: "narrative",
    language: "en-CA",
    languageName: "English (Canada) 🇨🇦",
    previewAudioUrl: "/audio/previews/lucas.mp3",
    avatarUrl: "/avatars/lucas.webp",
    supportedEmotions: ["neutral", "authoritative", "empathetic"],
    isPremium: false,
    tags: ["Canadian", "Documentary", "Educational", "Clear"],
  },

  // ===================== Hindi & South Asian =====================
  {
    id: "4f6b8d0e1f2a3b4c5d6e7f8a9b0c1d2e",
    name: "Aarav Sharma",
    gender: "male",
    category: "commercial",
    language: "hi-IN",
    languageName: "Hindi (India) 🇮🇳",
    previewAudioUrl: "/audio/previews/aarav.mp3",
    avatarUrl: "/avatars/aarav.webp",
    supportedEmotions: ["neutral", "cheerful", "dramatic"],
    isPremium: true,
    tags: ["Bollywood", "Commercial", "Hindi & Hinglish", "Energetic"],
  },
  {
    id: "5a7c9e1f2a3b4c5d6e7f8a9b0c1d2e3f",
    name: "Priya Kapoor",
    gender: "female",
    category: "narrative",
    language: "hi-IN",
    languageName: "Hindi (India) 🇮🇳",
    previewAudioUrl: "/audio/previews/priya.mp3",
    avatarUrl: "/avatars/priya.webp",
    supportedEmotions: ["neutral", "empathetic", "cheerful"],
    isPremium: true,
    tags: ["Hindi Storytelling", "Melodic", "Audiobook", "Warm"],
  },
  {
    id: "6b8d0f2a3b4c5d6e7f8a9b0c1d2e3f4a",
    name: "Rohan Varma",
    gender: "male",
    category: "conversational",
    language: "en-IN",
    languageName: "English (India) 🇮🇳",
    previewAudioUrl: "/audio/previews/rohan.mp3",
    avatarUrl: "/avatars/rohan.webp",
    supportedEmotions: ["neutral", "authoritative"],
    isPremium: false,
    tags: ["Indian English", "Tech Corporate", "Customer Service", "Clear"],
  },
  {
    id: "7c9e1a3b4c5d6e7f8a9b0c1d2e3f4a5b",
    name: "Ananya Deshmukh",
    gender: "female",
    category: "conversational",
    language: "en-IN",
    languageName: "English (India) 🇮🇳",
    previewAudioUrl: "/audio/previews/ananya.mp3",
    avatarUrl: "/avatars/ananya.webp",
    supportedEmotions: ["neutral", "cheerful", "empathetic"],
    isPremium: false,
    tags: ["Indian English", "Explainer Video", "E-learning", "Friendly"],
  },

  // ===================== Spanish (Spain & Latin America) =====================
  {
    id: "8d0f2b4c5d6e7f8a9b0c1d2e3f4a5b6c",
    name: "Mateo Silva",
    gender: "male",
    category: "commercial",
    language: "es-MX",
    languageName: "Spanish (Mexico) 🇲🇽",
    previewAudioUrl: "/audio/previews/mateo.mp3",
    avatarUrl: "/avatars/mateo.webp",
    supportedEmotions: ["neutral", "cheerful", "dramatic"],
    isPremium: true,
    tags: ["Latam Spanish", "Commercial", "Radio", "Dynamic"],
  },
  {
    id: "9e1a3c5d6e7f8a9b0c1d2e3f4a5b6c7d",
    name: "Sofia Navarro",
    gender: "female",
    category: "narrative",
    language: "es-ES",
    languageName: "Spanish (Spain) 🇪🇸",
    previewAudioUrl: "/audio/previews/sofia.mp3",
    avatarUrl: "/avatars/sofia.webp",
    supportedEmotions: ["neutral", "empathetic", "whispering"],
    isPremium: true,
    tags: ["Castilian Spanish", "Audiobook", "Documentary", "Warm"],
  },
  {
    id: "0f2b4d6e7f8a9b0c1d2e3f4a5b6c7d8e",
    name: "Diego Alvarez",
    gender: "male",
    category: "gaming",
    language: "es-MX",
    languageName: "Spanish (Mexico) 🇲🇽",
    previewAudioUrl: "/audio/previews/diego.mp3",
    avatarUrl: "/avatars/diego.webp",
    supportedEmotions: ["neutral", "dramatic", "excited"],
    isPremium: false,
    tags: ["Spanish Gaming", "Narrator", "Trailer", "Intense"],
  },

  // ===================== French =====================
  {
    id: "1a3c5e7f8a9b0c1d2e3f4a5b6c7d8e9f",
    name: "Camille Laurent",
    gender: "female",
    category: "commercial",
    language: "fr-FR",
    languageName: "French (France) 🇫🇷",
    previewAudioUrl: "/audio/previews/camille.mp3",
    avatarUrl: "/avatars/camille.webp",
    supportedEmotions: ["neutral", "cheerful", "whispering"],
    isPremium: true,
    tags: ["Parisian French", "Luxury", "Cosmetics", "Sensual"],
  },
  {
    id: "2b4d6f8a9b0c1d2e3f4a5b6c7d8e9f0a",
    name: "Antoine Dubois",
    gender: "male",
    category: "narrative",
    language: "fr-FR",
    languageName: "French (France) 🇫🇷",
    previewAudioUrl: "/audio/previews/antoine.mp3",
    avatarUrl: "/avatars/antoine.webp",
    supportedEmotions: ["neutral", "authoritative", "dramatic"],
    isPremium: true,
    tags: ["French Narration", "Philosophy", "Audiobook", "Refined"],
  },

  // ===================== German =====================
  {
    id: "3c5e7a9b0c1d2e3f4a5b6c7d8e9f0a1b",
    name: "Maximilian Richter",
    gender: "male",
    category: "executive",
    language: "de-DE",
    languageName: "German (Germany) 🇩🇪",
    previewAudioUrl: "/audio/previews/maximilian.mp3",
    avatarUrl: "/avatars/maximilian.webp",
    supportedEmotions: ["neutral", "authoritative"],
    isPremium: true,
    tags: ["German Corporate", "Engineering", "Precise", "Authoritative"],
  },
  {
    id: "4d6f8b0c1d2e3f4a5b6c7d8e9f0a1b2c",
    name: "Greta Weber",
    gender: "female",
    category: "conversational",
    language: "de-DE",
    languageName: "German (Germany) 🇩🇪",
    previewAudioUrl: "/audio/previews/greta.mp3",
    avatarUrl: "/avatars/greta.webp",
    supportedEmotions: ["neutral", "cheerful", "empathetic"],
    isPremium: false,
    tags: ["German Podcast", "Friendly", "Bright", "E-learning"],
  },

  // ===================== Japanese =====================
  {
    id: "5e7a9c1d2e3f4a5b6c7d8e9f0a1b2c3d",
    name: "Kenji Sato",
    gender: "male",
    category: "gaming",
    language: "ja-JP",
    languageName: "Japanese (Japan) 🇯🇵",
    previewAudioUrl: "/audio/previews/kenji.mp3",
    avatarUrl: "/avatars/kenji.webp",
    supportedEmotions: ["neutral", "dramatic", "excited"],
    isPremium: true,
    tags: ["Anime Hero", "Gaming", "Samurai", "Passionate"],
  },
  {
    id: "6f8b0d2e3f4a5b6c7d8e9f0a1b2c3d4e",
    name: "Yuki Tanaka",
    gender: "female",
    category: "conversational",
    language: "ja-JP",
    languageName: "Japanese (Japan) 🇯🇵",
    previewAudioUrl: "/audio/previews/yuki.mp3",
    avatarUrl: "/avatars/yuki.webp",
    supportedEmotions: ["neutral", "cheerful", "empathetic", "whispering"],
    isPremium: true,
    tags: ["VTuber", "Anime Kawaii", "Storytelling", "Cute"],
  },

  // ===================== Arabic & Middle East =====================
  {
    id: "7a9c1e3f4a5b6c7d8e9f0a1b2c3d4e5f",
    name: "Tariq Al-Mansoor",
    gender: "male",
    category: "narrative",
    language: "ar-SA",
    languageName: "Arabic (Saudi Arabia) 🇸🇦",
    previewAudioUrl: "/audio/previews/tariq.mp3",
    avatarUrl: "/avatars/tariq.webp",
    supportedEmotions: ["neutral", "authoritative", "dramatic"],
    isPremium: true,
    tags: ["Modern Standard Arabic", "Deep Narration", "Documentary", "Eloquent"],
  },
  {
    id: "8b0d2f4a5b6c7d8e9f0a1b2c3d4e5f6a",
    name: "Layla Haddad",
    gender: "female",
    category: "commercial",
    language: "ar-AE",
    languageName: "Arabic (United Arab Emirates) 🇦🇪",
    previewAudioUrl: "/audio/previews/layla.mp3",
    avatarUrl: "/avatars/layla.webp",
    supportedEmotions: ["neutral", "cheerful", "empathetic"],
    isPremium: false,
    tags: ["Gulf Arabic", "Commercial", "Modern", "Inspiring"],
  },

  // ===================== Portuguese & Italian =====================
  {
    id: "9c1e3a5b6c7d8e9f0a1b2c3d4e5f6a7b",
    name: "Gabriel Santos",
    gender: "male",
    category: "commercial",
    language: "pt-BR",
    languageName: "Portuguese (Brazil) 🇧🇷",
    previewAudioUrl: "/audio/previews/gabriel.mp3",
    avatarUrl: "/avatars/gabriel.webp",
    supportedEmotions: ["neutral", "cheerful", "excited"],
    isPremium: false,
    tags: ["Brazilian Portuguese", "Radio", "Commercial", "Upbeat"],
  },
  {
    id: "0d2f4b6c7d8e9f0a1b2c3d4e5f6a7b8c",
    name: "Chiara Moretti",
    gender: "female",
    category: "commercial",
    language: "it-IT",
    languageName: "Italian (Italy) 🇮🇹",
    previewAudioUrl: "/audio/previews/chiara.mp3",
    avatarUrl: "/avatars/chiara.webp",
    supportedEmotions: ["neutral", "cheerful", "dramatic"],
    isPremium: true,
    tags: ["Italian", "Fashion", "Commercial", "Expressive"],
  },
] as const;

export const DEFAULT_VOICE_ID = "7f92f8afb8ec43bf81429cc1c9199cb1";

export const DEFAULT_VOICE_SETTINGS = {
  stability: 0.75,
  similarityBoost: 0.85,
  style: 0.45,
  speed: 1.0,
  pitch: 0,
} as const;
